version: '3'

services:
    db:
        container_name: mariadb
        image: mariadb
        volumes:
          - ./mariadb_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: test
            MYSQL_DATABASE: testDB
            TZ: 'Europe/Paris'
        networks:
          - dolibarr_network
        ports:
          - "3306:3306"

    dolibarr:
        container_name: dolibarr
        depends_on:
          - db
        image: zimomar/project-2:2.0
        networks:
          - dolibarr_network
        ports:
          - "8888:80"

    load_balancer:
        container_name: lb
        build: load_balancer/ 
        depends_on:
          - dolibarr
          - db
        ports:
          - "8080:80"
        networks:
          - dolibarr_network
networks:
    dolibarr_network:
        driver: bridge
