version: '3'

services:
    db:
        container_name: mariadb
        image: mariadb
        volumes:
            - ./mariadb_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: test
            MYSQL_DATABASE: testDB
            TZ: 'Europe/Paris'
        networks:
            - dolibarr_network
        ports:
          - "3306:3306"

    dolibarr:
        container_name: dolibarr
        depends_on:
            - db
        image: zimomar/project-2:1.1
        networks:
            - dolibarr_network
        ports:
          - "80:80"

networks:
    dolibarr_network:
        driver: bridge
