apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  labels:
    app: mariadb
  name: mariadb-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
status: {}
