---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb
          ports:
            - containerPort: 3306
          env:
            #- name: MARIADB_RANDOM_ROOT_PASSWORD
#            - name: MARIADB_ALLOW_EMPTY_ROOT_PASSWORD
#              value: "0" # if it is 1 and root_password is set, root_password takes precedance
            - name: MARIADB_ROOT_PASSWORD
              value: secret
          volumeMounts:
            - name: mariadb-pv
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-pv
          persistentVolumeClaim:
            claimName: mariadb-pv-claim