version: '3'

services:
    mariadb:
        container_name: mariadb
        image: mariadb
        volumes:
          - ./mariadb_data:/var/lib/mysql
        restart: always
        environment:
            MARIADB_USER: dolibarr
            MARIADB_PASSWORD: dolibarr
            MARIADB_ROOT_PASSWORD: root
            TZ: 'Europe/Paris'
        networks:
          - dolibarr_network
        ports:
          - "3306:3306"

    dolibarr:
        container_name: dolibarr
        depends_on:
          - mariadb 
        image: zimomar/dolibarr
        networks:
          - dolibarr_network 
        volumes:
          - ./dolibarr/conf.php:/var/www/html/htdocs/conf/conf.php
          - ./dolibarr/documents:/var/www/html/documents

    load_balancer:
        container_name: lb
        image: nginx 
        depends_on:
          - dolibarr
        ports:
          - "80:80"
        networks:
          - dolibarr_network
        volumes:
          - ./load_balancer/nginx.conf:/etc/nginx/nginx.conf

networks:
    dolibarr_network:
        driver: bridge
