name: Docker Image CI

on:
  push:
    branches: [ "main", "cicd" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKERHUB_REPO: ${{ env.DOCKERHUB_REPO }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
      run: |
          echo $DOCKERHUB_REPO
