name: Docker Image CI

on:
  push:
    branches: [ "main", "cicd" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install doctl
      run: |
        sudo snap install doctl
    - name: Configure doctl
      run: |
        doctl auth init --access-token "${{ secrets.DIGITAL_OCEAN_TOKEN }}"
    - name: Import digital ocean cluster
      run: |
        doctl kubernetes cluster kubeconfig save "${{ secrets.DIGITAL_OCEAN_CLUSTER }}"
    - name: Get pods
      run: |
        kubectl get pods -o wide
#    - name: Build the Docker image
#      run: |
#          docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
#          cd docker/dolibarr && docker build -t ${{secrets.DOCKER_USER}}/${{vars.DOCKERHUB_REPO}}:latest .
#          docker push ${{secrets.DOCKER_USER}}/${{vars.DOCKERHUB_REPO}}:latest