name: Docker Image CI

on:
  push:
    branches: [ "main", "cicd" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
      run: |
          docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
          cd docker/dolibarr && docker build -t ${{vars.DOCKERHUB_REPO}} .
          docker push ${{vars.DOCKERHUB_REPO}}