name: Docker Image CI

on:
  push:
    branches: [ "main", "cicd" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install doctl
      run: |
        sudo snap install doctl
        sudo snap connect doctl:kube-config
        sudo snap connect doctl:ssh-keys :ssh-keys
        sudo snap connect doctl:dot-docker
    - name: Configure doctl and import digitalocean cluster
      run: |
        sudo doctl auth init --access-token "${{ secrets.DIGITAL_OCEAN_TOKEN }}"


#    - name: Build the Docker image
#      run: |
#          docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
#          cd docker/dolibarr && docker build -t ${{secrets.DOCKER_USER}}/${{vars.DOCKERHUB_REPO}}:latest .
#          docker push ${{secrets.DOCKER_USER}}/${{vars.DOCKERHUB_REPO}}:latest