name: Docker Image CI

on:
  push:
    branches: [ "main", "cicd" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
      env:
        DOCKERHUB_REPO: ${{ env.DOCKERHUB_REPO }}
      run: |
          echo $DOCKERHUB_REPO
